Repository AsishRajen007/OLLALA, pull requests merged in 2022-10, with the labels that each got.

#1 Create EASY_PEASY
  EASY_PEASY
Labels: good first issue, ACCEPTED, hacktoberfest accepted

#2 terminal.cpp
  TErminal.cpp
Labels: good first issue, ACCEPTED, hacktoberfest-accepted

#3 plane.cpp
  plane.cpp
Labels: good first issue, ACCEPTED, hacktoberfest-accepted

#6 pol
  yup.html
Labels: ACCEPTED, hacktoberfest-accepted

#7 Create hulala.html
  hulala.html
Labels: hacktoberfest-accepted

#8 Create Dance.html
  Dance.html
Labels: hacktoberfest-accepted

#10 Create Fond.html
  Fond.html
Labels: ACCEPTED, hacktoberfest-accepted

#9 Add Simple Calculator with PHP
  Simple_Calculator.php
Labels: ACCEPTED, hacktoberfest-accepted
